eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka:
      value: true
    fetch-registry:
      value: true
    instance:
      hostname: localhost

spring:
  application:
    name: API_GATEWAY
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:9999


    gateway:
      routes:
        - id: UserService
          uri: lb://UserService
          predicates:
            - Path=/users/**
        - id: ProductService
          uri: lb://ProductService
          predicates:
            - Path=/products/**
        - id: OrderService
          uri: lb://OrderService
          predicates:
            - Path=/orders/**
